import { Paper } from "./types";

export const paper: Paper[] = [
  {
    id: "3fa85f64-5717-4562-b3fc-2c963f66aafd",
    paper_text:
      "This is the first sentence of the document. There are more words beyond this point, but this snippet is under 100 words.",
    paper_url:
      "https://www.media.wmg-is.com/media/portal/media/cms/docs/201202/curreny-quote-sheet_1330379143004.pdf",
    notes: [
      {
        note: "This is a note generated by an LLM based on the content of the PDF.",
        page_numbers: [1],
      },
    ],
    paper_title: "Sample Document",
    created_at: "2024-04-20",
  },
  {
    id: "de2a10c2-9afe-4c6c-88be-f2822f3f3b11",
    paper_text:
      "This is some text from a different PDF. It highlights a key point about a specific topic.",
    paper_url:
      "https://www.media.wmg-is.com/media/portal/media/cms/docs/201202/curreny-quote-sheet_1330379143004.pdf",
    notes: [
      {
        note: "The LLM identified a key point about the topic.",
        page_numbers: [3],
      },
    ],
    paper_title: "Important Findings in Research",
    created_at: "2024-04-18",
  },
  {
    id: "7e4d18c0-2ac4-4a9b-8ebb-2b87f57c4f19",
    paper_text:
      "Here's a snippet from a legal document. It emphasizes a specific clause.",
    paper_url:
      "https://www.media.wmg-is.com/media/portal/media/cms/docs/201202/curreny-quote-sheet_1330379143004.pdf",
    notes: [
      {
        note: "The LLM highlighted a specific clause within the contract.",
        page_numbers: [5, 6],
      },
    ],
    paper_title: "Contract Agreement",
    created_at: "2024-04-15",
  },
  {
    id: "9b1e23fe-7c2c-4f3b-a8c3-9b29f9d98e23",
    paper_text:
      "This document talks about interesting historical events. It mentions a specific date.",
    paper_url:
      "https://www.media.wmg-is.com/media/portal/media/cms/docs/201202/curreny-quote-sheet_1330379143004.pdf",
    notes: [
      {
        note: "The LLM identified a specific date mentioned in the historical timeline.",
        page_numbers: [2],
      },
    ],
    paper_title: "Historical Timeline",
    created_at: "2024-04-12",
  },
  {
    id: "e4d3b19e-ba88-4e2e-87b0-eb2bfa9e2c32",
    paper_text:
      "This scientific report details a new discovery. It focuses on a particular finding.",
    paper_url:
      "https://www.media.wmg-is.com/media/portal/media/cms/docs/201202/curreny-quote-sheet_1330379143004.pdf",
    notes: [
      {
        note: "The LLM highlighted a new discovery mentioned in the scientific report.",
        page_numbers: [1, 3],
      },
    ],
    paper_title: "Research Report: New Discovery",
    created_at: "2024-04-10",
  },
  {
    id: "5f17cffc-23aa-4edf-8a8e-ac6b3c3c2ece",
    paper_text:
      "This literary work contains beautiful imagery. It describes a specific scene.",
    paper_url:
      "https://www.media.wmg-is.com/media/portal/media/cms/docs/201202/curreny-quote-sheet_1330379143004.pdf",
    notes: [
      {
        note: "The LLM identified beautiful imagery describing a particular scene.",
        page_numbers: [15, 16],
      },
    ],
    paper_title: "A Captivating Novel",
    created_at: "2024-04-08",
  },
  {
    id: "1ca56b92-1d1f-4d09-9876-d29c17f1a09e",
    paper_text:
      "This excerpt from a news article discusses a recent development. It mentions a key player.",
    paper_url:
      "https://www.media.wmg-is.com/media/portal/media/cms/docs/201202/curreny-quote-sheet_1330379143004.pdf",
    notes: [
      {
        note: "The LLM identified a key player involved in the recent development.",
        page_numbers: [1],
      },
    ],
    paper_title: "Breaking News",
    created_at: "2024-04-05",
  },
  {
    id: "08b721e4-abec-4782-a9c0-b78d2f1f1f22",
    paper_text:
      "This blog post offers valuable advice on a specific topic. It highlights a key takeaway.",
    paper_url:
      "https://www.media.wmg-is.com/media/portal/media/cms/docs/201202/curreny-quote-sheet_1330379143004.pdf",
    notes: [
      {
        note: "The LLM identified a key takeaway or actionable advice from the blog post.",
        page_numbers: [2],
      },
    ],
    paper_title: "Life Hacks for Efficiency",
    created_at: "2024-04-03",
  },
  {
    id: "f2784c10-b32e-4e1d-b08e-7c9727f54f98",
    paper_text:
      "This data analysis report presents interesting trends. It focuses on a specific statistic.",
    paper_url:
      "https://www.media.wmg-is.com/media/portal/media/cms/docs/201202/curreny-quote-sheet_1330379143004.pdf",
    notes: [
      {
        note: "The LLM identified an interesting statistic from the data analysis.",
        page_numbers: [4, 5],
      },
    ],
    paper_title: "Market Trends Report",
    created_at: "2024-04-01",
  },
  {
    id: "b639e1d2-42c8-4f9b-a0ab-d7932f2c1b1a",
    paper_text:
      "This email thread contains important information. It mentions a specific deadline.",
    paper_url:
      "https://www.media.wmg-is.com/media/portal/media/cms/docs/201202/curreny-quote-sheet_1330379143004.pdf",
    notes: [
      {
        note: "The LLM identified an important deadline mentioned in the email thread.",
        page_numbers: [1],
      },
    ],
    paper_title: "Important Project Update",
    created_at: "2024-03-29",
  },
];
